apiVersion: v1
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: master
    name: master-35.190.203.17
    namespace: weavek8sops
  spec:
    versions:
      kubelet: 1.16.11
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.132.15.202
          port: 22
        public:
          address: 35.190.203.17
          port: 22
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      set: worker
    name: worker-35.233.16.221
    namespace: weavek8sops
  spec:
    versions:
      kubelet: 1.16.11
    providerSpec:
      value:
        apiVersion: baremetalproviderspec/v1alpha1
        kind: BareMetalMachineProviderSpec
        private:
          address: 10.132.15.205
          port: 22
        public:
          address: 35.233.16.221
          port: 22
kind: List
