apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: gitlab-token
  namespace: wkp-workspaces
spec:
  encryptedData:
    token: AgAkH29I6/svIqCOz99ZAFLYzA4E6ewFcrjXfrlh02JM3igG3g3LcP5TYFRRCbST3DfFxq+XMhEzRdUFGRjwyNF9yAXKxAYjx03bQi3CEO3BL1bdDLxcvm2w5hcDqxmqSSvsgF4sT1XViRjF+sy3i42ww0t+shIEBD7vleD4IekJf5eENe99Iq3vZAl5fMrDB2EbEivJqXAfnakU24IRkXzNluOcnmexGv4y4INxa8xamX3Pq4RecWHPc9URIWPG+SmGHd4D7UsZ4AqkoC4kxnUVYyxqNYR2LsN4z8D2bb3H4LvL6j/Lcmuviao+2YviSfYsHfXdWe5JhblQlRIIlG9r72PHE04clOQ/QYiXL9Jtkm8bMrZr8ecqkhDs324bn/1Q5SCRuJlXVvnTWjEYmCZ7HNfOMWvj5SNm3ulWjJpxoMv4E/E9mDkd5U+zX4peaqxOstQkZvWQbagwEXJrn7+4fHw/OoolrEogsD76Ez3wM4zDs/PKial80lDtsrYOuwcFcyOI1kslAkel1My/woBJeAWoSqVnMNeg9zWXqgyG1zH2p2nRz94AeuOeeuEZ4h1xcFFJfpWvlTBIO7yEWil8ewlfV12IBDipAYnT8xEVKf71oFv1pgpLamGalU+YLRIzPJ1x1NElQw9fd7AguVezSQMS5CwzrBY77+h8E/HTwLS0Q1RfJJkPbnA2fbART4+gU9x68a9/iIWMEpW3UVDvjbyOWQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
        wkp.weave.works/git-provider-hostname: gitlab.com
        wkp.weave.works/git-provider-type: gitlab
      creationTimestamp: null
      labels:
        wkp.weave.works/type: git-provider-token
      name: gitlab-token
      namespace: wkp-workspaces
status: {}

